# Generated by Django 3.2.7 on 2021-09-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
