# Generated by Django 3.2.7 on 2021-09-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_voting_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='close date'),
        ),
    ]
