# Generated by Django 3.2.7 on 2021-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enable_closed_date',
            field=models.BooleanField(default=False, verbose_name='enable close date'),
        ),
    ]
